import '@/app/globals.css'
import type { Metadata } from 'next'
import {Suspense} from "react";
import { Inter } from 'next/font/google'
import Provider from "@/app/Provider"
import Header from "@/components/header/Header"
import Loading from "@/app/Loading";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '지점몰 테스트',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {/*<Loading></Loading>*/}
          <Suspense fallback={<Loading></Loading>}>
            <Header></Header>
            {children}
          </Suspense>
        </Provider>
      </body>
    </html>
  )
}
